mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include


urlpatterns = [
    path('admin/', admin.site.urls),
    path('rent',  include('rent.urls'))
]

mysite/rent/urls.py
from django.urls import path
from .views import rental, login_page, register_page, logout_page, \
    cart, book_to_cart, film_to_cart, cd_to_cart
from . import views

app_name = 'rent'
urlpatterns = [
    # path('', home, name='home'),
    path('', views.HomeView.as_view(), name='home'),
    path('/<int:rental_id>', rental, name='rental'),
    path('/cart', cart, name='cart'),
    path('/login', login_page, name='login'),
    path('/register', register_page, name='register'),
    path('/logout', logout_page, name='logout'),
    path('/booktocart/<int:book_id>', book_to_cart, name='book_to_cart'),
    path('/filmtocart/<int:film_id>', film_to_cart, name='film_to_cart'),
    path('/cdtocart/<int:cd_id>', cd_to_cart, name='cd_to_cart')

]

mysite/rent/models.py
from django.db import models
from django.utils.translation import gettext as _
from django.contrib import admin
from django.contrib.auth.models import User
from datetime import timedelta, date


# Create your models here.
PROVINCES = (
    ('DSL', 'dolnośląskie'), ('KP', 'kujawsko-pomorskie'), ('LBL', 'lubelskie'), ('LBU', 'lubuskie'),
    ('LDZ', 'łódzkie'), ('MLP', 'małopolskie'), ('MAZ', 'mazowieckie'), ('OPO', 'opolskie'), ('PKR', 'podkarpackie'),
    ('PDL', 'podlaskie'), ('POM', 'pomorskie'), ('SL', 'śląskie'), ('SW', 'świętokrzyskie'),
    ('WM', 'warmińsko-mazurskie'), ('WLKP', 'wielkopolskie'), ('ZPM', 'zachodniopomorskie')
)


class Rental(models.Model):
    name = models.CharField(max_length=30)
    street = models.CharField(_('Street'), max_length=30)
    city = models.CharField(_('City'), max_length=30)
    province = models.CharField(_('Province'), choices=PROVINCES, max_length=20)
    postal_code = models.CharField(_('Postal Code'), max_length=6)

    def __str__(self):
        return self.name

    @admin.display(
        ordering='city',
        description='Address'
    )
    def get_address(self):
        return f'{self.city}, ul.{self.street}'


class Product(models.Model):
    rental = models.ForeignKey(Rental, on_delete=models.CASCADE)
    title = models.CharField(max_length=50)
    author = models.CharField(max_length=20)

    class Meta:
        abstract = True

    def __str__(self):
        return f'{self.title}, {self.author}'


class Book(Product):
    book_genre = models.CharField(max_length=30)
    publishing_house = models.CharField(max_length=20)
    isbn = models.CharField(max_length=17, blank=True)


class Film(Product):
    film_genre = models.CharField(max_length=20)
    duration = models.DurationField()


class CD(Product):
    music_genre = models.CharField(max_length=20)
    track_list = models.TextField()
    duration = models.DurationField


class Customer(models.Model):
    user = models.OneToOneField(User, null=True, on_delete=models.CASCADE)
    name = models.CharField(max_length=200, null=True)
    phone = models.CharField(max_length=200, null=True)
    email = models.CharField(max_length=200, null=True)

    def __str__(self):
        return str(self.name)


class Rent(models.Model):
    customer = models.ForeignKey(Customer, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    # books = models.ForeignKey(Book, on_delete=models.CASCADE)
    # films = models.ForeignKey(Film, on_delete=models.CASCADE)
    # cds = models.ForeignKey(CD, on_delete=models.CASCADE)

    date_of_loan = models.DateField(default=date.today())
    date_of_return = None

    def expected_date_of_return(self):
        return (self.date_of_loan + timedelta(days=30)).strftime("%Y-%m-%d")

    def __str__(self):
        return f'{self.product}, {self.expected_date_of_return()}'


class Cart(models.Model):
    rent = models.ForeignKey(Rent, on_delete=models.CASCADE)

    def __str__(self):
        return str(self.rent)

    # def add_to_cart(self, book_id):
    #     book = Book.objects.get(pk=book_id)
    #     try:
    #         preexisting_order = Rental.objects.get(book=book, cart=self)
    #         preexisting_order.quantity += 1
    #         preexisting_order.save()
    #     except BookOrder.DoesNotExist:
    #         new_order = BookOrder.objects.create(
    #             book=book,
    #             cart=self,
    #             quantity=1
    #         )
    #         new_order.save()


# class Book(models.Model):
#     rental = models.ForeignKey(Rental, on_delete=models.CASCADE)
#     author = models.CharField(max_length=20)
#     title = models.CharField(max_length=50)
#     book_genre = models.CharField(choices=BOOK_GENRE, max_length=30)
#     publishing_house = models.CharField(max_length=20)
#     ISBN = models.CharField(max_length=17, blank=True)
#
#     date_of_loan = None
#
#     def __str__(self):
#         return f'{self.author}, {self.title}'
#
#     @admin.display(
#         boolean=True,
#         description='Available'
#     )
#     def check_availability(self):
#         if self.date_of_loan is None:
#             return True
#         else:
#             return f'Unavailable, expected date of return: {self.get_expected_date_of_return()}'
#
#     def get_expected_date_of_return(self):
#         if self.date_of_loan is not None:
#             return (self.date_of_loan + timedelta(days=30)).strftime("%Y-%m-%d")
#         else:
#             raise Exception('Object is not loaned.')
#

# class Film(models.Model):
#     rental = models.ForeignKey(Rental, on_delete=models.CASCADE)
#     director = models.CharField(max_length=20)
#     title = models.CharField(max_length=50)
#     film_genre = models.CharField(max_length=20)
#     duration = models.DurationField()
#
#     date_of_loan = None
#
#     def __str__(self):
#         return f'{self.director, self.title}'
#
#     @admin.display(
#         boolean=True,
#         description='Available'
#     )
#     def check_availability(self):
#         if self.date_of_loan is None:
#             return True
#         else:
#             return f'Unavailable, expected date of return: {self.get_expected_date_of_return()}'
#
#     def get_expected_date_of_return(self):
#         if self.date_of_loan is not None:
#             return (self.date_of_loan + timedelta(days=30)).strftime("%Y-%m-%d")
#         else:
#             raise Exception('Object is not loaned.')
#
#
# class CD(models.Model):
#     rental = models.ForeignKey(Rental, on_delete=models.CASCADE)
#     author = models.CharField(max_length=20)
#     title = models.CharField(max_length=50)
#     music_genre = models.CharField(max_length=20)
#     track_list = models.TextField()
#     duration = models.DurationField
#
#     date_of_loan = None
#
#     def __str__(self):
#         return f'{self.author}, {self.title}'
#
#     @admin.display(
#         boolean=True,
#         description='Available'
#     )
#     def check_availability(self):
#         if self.date_of_loan is None:
#             return True
#         else:
#             return f'Unavailable, expected date of return: {self.get_expected_date_of_return()}'
#
#     def get_expected_date_of_return(self):
#         if self.date_of_loan is not None:
#             return (self.date_of_loan + timedelta(days=30)).strftime("%Y-%m-%d")
#         else:
#             raise Exception('Object is not loaned.')

mysite/rent/forms.py
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from django.forms import ModelForm
from .models import Customer


class CreateUserForm(UserCreationForm):
    class Meta:
        model = User
        fields = ['username', 'password']


class CreateCustomerForm(ModelForm):
    class Meta:
        model = Customer
        fields = '__all__'
        exclude = ['user']

mysite/rent/views.py
from django.shortcuts import get_object_or_404, render
from .models import Rental, Customer, Book, Film, CD, Cart
from django.shortcuts import render, redirect
from django.contrib.auth import login, logout, authenticate
from .forms import CreateUserForm, CreateCustomerForm
from django.utils import timezone
from django.core.exceptions import ObjectDoesNotExist
from django.views import generic



class HomeView(generic.ListView):
    template_name = 'rent/home.html'
    context_object_name = 'rentals'

    def get_queryset(self):
        """
        Excludes any questions that aren't published yet.
        """
        return Rental.objects.all()


def rental(request, rental_id):
    rent = get_object_or_404(Rental, pk=rental_id)
    books = rent.book_set.all()
    films = rent.film_set.all()
    cds = rent.cd_set.all()
    context = {'books': books, 'films': films, 'cds': cds}
    return render(request, 'rent/rental.html', context)


# def cart(request):
#     if request.user.is_authenticated:
#         return render(request, 'rent/cart.html')
#     else:
#         return redirect('/rent')


def login_page(request):
    if request.user.is_authenticated:
        return redirect('/rent')
    else:
        if request.method == "POST":
            username = request.POST.get('username')
            password = request.POST.get('password')
            user = authenticate(request, username=username, password=password)
            if user is not None:
                print("working")
                login(request, user)
                return redirect('/rent')
        return render(request, 'rent/login.html')


def logout_page(request):
    logout(request)
    return redirect('/rent')


def register_page(request):
    if request.user.is_authenticated:
        return redirect('home')
    else:
        form = CreateUserForm()
        cust_form = CreateCustomerForm()
        if request.method == 'POST':
            form = CreateUserForm(request.POST)
            cust_form = CreateCustomerForm(request.POST)
            if form.is_valid() and cust_form.is_valid():
                user = form.save()
                customer = cust_form.save(commit=False)
                customer.user = user
                customer.save()
                return redirect('login')
        context = {
            'form': form,
            'cust_form': cust_form,
        }
        return render(request, 'rent/register.html', context)


# def cart(request):
#     if request.user.is_authenticated:
#         car = Customer.objects.all()
#         return render(request, 'rent/cart.html', {'cart': car})
#     else:
#         return redirect('/rent')


def cart(request):
    cust = Customer.objects.filter(user=request.user)
    for c in cust:
        carts = Cart.objects.all()
        for car in carts:
            if car.customer == c:
                context = {
                    'cart': cart
                }
                return render(request, 'rent/cart.html', context)

#
# def book_to_cart(request, book_id):
#     book = Book.objects.get(id=book_id)
#     cust = Customer.objects.filter(user=request.user)
#     Book.date_of_loan = timezone.now()
#
#     for c in cust:
#         carts = Cart.objects.all()
#         req_cart = ''
#         for car in carts:
#             if car.customer == c:
#                 req_cart = car
#                 break
#         if req_cart == '':
#             req_cart = Cart.objects.create(
#                 customer=c,
#             )
#         req_cart.books.add(book)
#     return redirect('/rent/cart')


def book_to_cart(request, book_id):
    if request.user.is_authenticated():
        book = get_object_or_404(Book, pk=book_id)
        cart, created = Cart.objects.get_or_create(user=request.user, active=True)
        cart.add_to_cart(book_id)
        return redirect('/rent/cart')
    else:
        return redirect('/rent')


def film_to_cart(request, film_id):
    film = Film.objects.get(id=film_id)
    cust = Customer.objects.filter(user=request.user)
    Film.date_of_loan = timezone.now()
    for c in cust:
        carts = Cart.objects.all()
        req_cart = ''
        for car in carts:
            if car.customer == c:
                req_cart = car
                break
        if req_cart == '':
            req_cart = Cart.objects.create(
                customer=c,
            )
        req_cart.films.add(film)
    return redirect('/rent/cart')


def cd_to_cart(request, cd_id):
    cd = CD.objects.get(id=cd_id)
    cust = Customer.objects.filter(user=request.user)
    CD.date_of_loan = timezone.now()

    for c in cust:
        carts = Cart.objects.all()
        req_cart = ''
        for car in carts:
            if car.customer == c:
                req_cart = car
                break
        if req_cart == '':
            req_cart = Cart.objects.create(
                customer=c,
            )
        req_cart.cds.add(cd)
    return redirect('/rent/cart')

mysite/rent/templates/rent/cart.html
<!DOCTYPE html>
<html lang="en">
{% block content %}

<html>
<head>
<style>
ul {
	list-style-type: none;
	margin: 0;
	padding: 0;
	overflow: hidden;
}

li {
	float: left;
}

li a {
	display: block;
	padding: 8px;
	background-color: #30d5c8;
}
</style>
</head>
<body>

<ul>
	<li><a href="{% url 'rent:home' %}">HOME</a></li>
	<li><a href="{% url 'rent:cart' %}"> CART</a></li>
	<li><a href="{% url 'rent:login' %}">LOGIN</a></li>
	<li><a href="{% url 'rent:register' %}">REGISTER</a></li>
	<li><a href="{% url 'rent:logout' %}">LOGOUT</a></li>
</ul>

</body>
</html>

<br>


<div class="container">
<div class="container row">
	<div class="col-lg-10">
		<h3>BOOKS:</h3>
		<div class="card card-body">
			<table class="table table-sm">
				<tr>
					<th> <Title></Title> </th>
					<th> Author </th>
					<th> Genre </th>
					<th> Publishing house </th>
					<th> Return date </th>
					<th></th>
				</tr>
				{% for book in books %}
				<tr>
					<td><b>{{book.title}}</b> </td>
					<td>{{book.author}} </td>
					<td>{{book.book_genre}} </td>
					<td>{{book.publishing_house}}</td>
					<td>{{book.get_expected_date_of_return}}</td>
					<td><a class="btn btn-sm btn-info" href="{% url 'rent:rental' book.id %}">Return </a> </td>
				</tr>
				{% endfor %}
			</table>
		</div>
        <h3>FILMS:</h3>
		<div class="card card-body">
			<table class="table table-sm">
				<tr>
					<th> <Title></Title> </th>
					<th> Director </th>
					<th> Genre </th>
					<th> Return date </th>
					<th></th>
				</tr>
				{% for film in films %}
				<tr>
					<td><b>{{film.title}}</b> </td>
					<td>{{film.director}} </td>
					<td>{{film.film_genre}} </td>
					<td>{{film.get_expected_date_of_return}}</td>
					<td><a class="btn btn-sm btn-info" href="{% url 'rent:rental' film.id %}">Rent </a> </td>
				</tr>
				{% endfor %}
			</table>
		</div>
        <h3>CDs:</h3>
		<div class="card card-body">
			<table class="table table-sm">
				<tr>
					<th> <Title></Title> </th>
					<th> Author </th>
					<th> Genre </th>
					<th> Return date </th>
					<th></th>
				</tr>
				{% for cd in cds %}
				<tr>
					<td><b>{{cd.title}}</b> </td>
					<td>{{cd.director}} </td>
					<td>{{cd.music_genre}} </td>
					<td>{{cd.get_expected_date_of_return}}</td>
					<td><a class="btn btn-sm btn-info" href="{% url 'rent:rental' cd.id %}">Rent </a> </td>
				</tr>
				{% endfor %}
			</table>
		</div>
	</div>


</div>
</div>

{% endblock %}

mysite/rent/templates/rent/home.html
<!DOCTYPE html>
<html lang="en">
{% block content %}

<html>
<head>
<style>
ul {
	list-style-type: none;
	margin: 0;
	padding: 0;
	overflow: hidden;
}

li {
	float: left;
}

li a {
	display: block;
	padding: 8px;
	background-color: #30d5c8;
}
</style>
</head>
<body>

<ul>
	<li><a href="{% url 'rent:home' %}">HOME</a></li>
	<li><a href="{% url 'rent:cart' %}"> CART</a></li>
	<li><a href="{% url 'rent:login' %}">LOGIN</a></li>
	<li><a href="{% url 'rent:register' %}">REGISTER</a></li>
	<li><a href="{% url 'rent:logout' %}">LOGOUT</a></li>
</ul>

</body>
</html>



<br>

<div class="container">
<div class="container row">
	<div class="col-lg-10">
		<h3>RENTALS:</h3>
		<div class="card card-body">
			<table class="table table-sm">
				<tr>
					<th><Title></Title></th>
					<th>Address</th>
                    <th></th>
				</tr>
                {% for rental in rentals %}
		        <tr>
					<td><b>{{rental.name}}</b> </td>
                    <td>{{rental.get_address}} </td>
                    <td><a class="btn btn-sm btn-info" href="{% url 'rent:rental' rental.id %}">Choose </a> </td>
				</tr>
				{% endfor %}
			</table>
		</div>
	</div>


</div>
</div>

{% endblock %}

mysite/rent/templates/rent/login.html
{% load static%}
{% block content %}
<div class="container jumbotron">
    <form method="POST" action="">
        {% csrf_token %}
        <p><input type="text" name="username" placeholder="Username"></p>
        <p><input type="password" name="password" placeholder="Password" ></p>
        <input class="btn btn-success" type="submit" value="Login">
        <p>Do not have an account? <a  href="{% url 'rent:register' %}">Register now </a></p>
    </form>
</div>
{% endblock %}

mysite/rent/templates/rent/register.html
{% load static%}
{% block content %}
<div class="container jumbotron">
    <form method="POST" action="" >
        {% csrf_token %}
        {{form.as_p}}
        {{cust_form.as_p}} 
       
        <input class="btn btn-success" type="submit" value="Register Account">
    </form>
</div>
{% endblock %}

mysite/rent/templates/rent/rental.html
<!DOCTYPE html>
<html lang="en">
{% block content %}

<html>
<head>
<style>
ul {
	list-style-type: none;
	margin: 0;
	padding: 0;
	overflow: hidden;
}

li {
	float: left;
}

li a {
	display: block;
	padding: 8px;
	background-color: #30d5c8;
}
</style>
</head>
<body>

<ul>
	<li><a href="{% url 'rent:home' %}">HOME</a></li>
	<li><a href="{% url 'rent:cart' %}"> CART</a></li>
	<li><a href="{% url 'rent:login' %}">LOGIN</a></li>
	<li><a href="{% url 'rent:register' %}">REGISTER</a></li>
	<li><a href="{% url 'rent:logout' %}">LOGOUT</a></li>
</ul>

</body>
</html>

<br>

<div class="container">
<div class="container row">
	<div class="col-lg-10">
		<h3>BOOKS:</h3>
		<div class="card card-body">
			{% if books %}
				<table class="table table-sm">
					<tr>
						<th> <Title></Title> </th>
						<th> Author </th>
						<th> Genre </th>
						<th> Publishing house </th>
						<th></th>
					</tr>
					{% for book in books %}
					<tr>
						<td><b>{{book.title}}</b> </td>
						<td>{{book.author}} </td>
						<td>{{book.book_genre}} </td>
						<td>{{book.publishing_house}}</td>
						<td><a class="btn btn-sm btn-info" href="{% url 'rent:book_to_cart' book.id %}">Rent </a> </td>
					</tr>
					{% endfor %}
				</table>
			{% else %}
				<p>No books are available.</p>
			{% endif %}
		</div>
        <h3>FILMS:</h3>
		<div class="card card-body">
			{% if films %}
				<table class="table table-sm">
					<tr>
						<th> <Title></Title> </th>
						<th> Director </th>
						<th> Genre </th>
						<th></th>
					</tr>
					{% for film in films %}
					<tr>
						<td><b>{{film.title}}</b> </td>
						<td>{{film.author}} </td>
						<td>{{film.film_genre}} </td>
						<td><a class="btn btn-sm btn-info" href="{% url 'rent:film_to_cart' film.id %}">Rent </a> </td>
					</tr>
					{% endfor %}
				</table>
			{% else %}
    			<p>No films are available.</p>
			{% endif %}
		</div>
        <h3>CDs:</h3>
		<div class="card card-body">
			{% if cds %}
				<table class="table table-sm">
					<tr>
						<th> <Title></Title> </th>
						<th> Author </th>
						<th> Genre </th>
						<th></th>
					</tr>
					{% for cd in cds %}
					<tr>
						<td><b>{{cd.title}}</b> </td>
						<td>{{cd.author}} </td>
						<td>{{cd.music_genre}} </td>
						<td><a class="btn btn-sm btn-info" href="{% url 'rent:cd_to_cart' cd.id %}">Rent </a> </td>
					</tr>
					{% endfor %}
				</table>
			{% else %}
				<p> No CDs are available. </p>
			{% endif %}
		</div>


	</div>


</div>
</div>

{% endblock %}